package com.mohammad.scheduleddownloader
import android.app.*
import android.content.*
import android.net.Uri
import android.os.*
import android.provider.MediaStore
import androidx.core.app.NotificationCompat
import kotlinx.coroutines.*
import java.net.HttpURLConnection
import java.net.URL
class DownloadService:Service(){ private val scope=CoroutineScope(Dispatchers.IO+SupervisorJob()); override fun onCreate(){super.onCreate();Notifications.setup(this);startForeground(7,NotificationCompat.Builder(this,Notifications.CHANNEL).setSmallIcon(R.drawable.ic_launcher).setContentTitle("Scheduled Downloader").setContentText("در حال آماده‌سازی دانلود").build())} override fun onStartCommand(i:Intent?,f:Int,s:Int):Int{val id=i?.getLongExtra("id",0)?:0;scope.launch{download(id)};return START_NOT_STICKY} private suspend fun download(id:Long){val dao=AppDb.get(this).taskDao();val t=dao.get(id)?:return;dao.update(t.copy(status="STARTING",message="در حال شروع"));Notifications.show(this,id.toInt(),"شروع دانلود",t.url);try{val con=URL(t.url).openConnection() as HttpURLConnection;con.connectTimeout=20000;con.readTimeout=60000;con.requestMethod="GET";con.connect();if(con.responseCode !in 200..299)error("HTTP ${con.responseCode}");val name=safeName(t.filename?:fromDisposition(con.getHeaderField("Content-Disposition"))?:URL(t.url).path.substringAfterLast('/').ifBlank{"download"});val out:java.io.OutputStream;var uri:Uri?=null;if(Build.VERSION.SDK_INT>=29){val v=ContentValues().apply{put(MediaStore.Downloads.DISPLAY_NAME,name);put(MediaStore.Downloads.MIME_TYPE,con.contentType?:"application/octet-stream");put(MediaStore.Downloads.RELATIVE_PATH,"Download/ScheduledDownloads");put(MediaStore.Downloads.IS_PENDING,1)};uri=contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v)?:error("Storage unavailable");out=contentResolver.openOutputStream(uri)?:error("Cannot open output")}else{val dir=Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).resolve("ScheduledDownloads");dir.mkdirs();out=java.io.FileOutputStream(dir.resolve(name))};con.inputStream.use{input->out.use{output->input.copyTo(output)}};if(uri!=null)contentResolver.update(uri,ContentValues().apply{put(MediaStore.Downloads.IS_PENDING,0)},null,null);dao.update(t.copy(status="COMPLETED",message="ذخیره شد: $name",completedAt=System.currentTimeMillis()));Notifications.show(this,id.toInt(),"دانلود کامل شد",name)}catch(e:Exception){dao.update(t.copy(status="FAILED",message=e.message?:"خطای ناشناخته",completedAt=System.currentTimeMillis()));Notifications.show(this,id.toInt(),"دانلود ناموفق",e.message?:"خطای ناشناخته")}finally{stopSelf()}} private fun fromDisposition(v:String?)=v?.substringAfter("filename=","")?.trim('"',' ');private fun safeName(v:String)=v.substringAfterLast('/').replace(Regex("[^A-Za-z0-9._ -]"),"_").ifBlank{"download"};override fun onBind(i:Intent?)=null;override fun onDestroy(){scope.cancel();super.onDestroy()} }
